// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc7LSeemwW-nlF7FG3BZOvdAESVZ_Bce4',
    appId: '1:267763038150:web:6427da0b1c6ed60d09e4c7',
    messagingSenderId: '267763038150',
    projectId: 'todousers-61ee8',
    authDomain: 'todousers-61ee8.firebaseapp.com',
    storageBucket: 'todousers-61ee8.appspot.com',
    measurementId: 'G-ZKBX2D0MVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfcAB8YO0GeqVpXc3GQ4Ef-fQyeh0fR8',
    appId: '1:267763038150:android:ca07490b9464088309e4c7',
    messagingSenderId: '267763038150',
    projectId: 'todousers-61ee8',
    storageBucket: 'todousers-61ee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qTQVu_GFRxuHKM3GID1eAhytL2DImyU',
    appId: '1:267763038150:ios:43c29e6689468b7a09e4c7',
    messagingSenderId: '267763038150',
    projectId: 'todousers-61ee8',
    storageBucket: 'todousers-61ee8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
